// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frmjqexnjgkhydgjnwew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZybWpxZXhuamdraHlkZ2pud2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTkzMDcsImV4cCI6MjA2MjgzNTMwN30.0LfozVYrG5TTqic-Gw5Tap31ETKgvzjayUtw74zRqJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);